Repository w3c/vc-jose-cose, pull requests merged in 2024-08, with the labels that each got.

#290 update all examples to use proper data urls
  index.html
Labels: class 1

#294 Add reference to NIST SP-800-122
  index.html
Labels: editorial

#291 Use of nbf is NOT RECOMMENDED
  index.html
Labels: normative
